language: python
python:
    - "2.7"
    # - "3.3"

env:
    global:
        - PACKAGE="AlignTab"
    matrix:
        # - SUBLIME_TEXT_VERSION="2"
        - SUBLIME_TEXT_VERSION="3"

before_install:
    - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh

install:
    - sh -e travis.sh $SUBLIME_TEXT_VERSION $PACKAGE

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - UNITTESTING=$HOME/.config/sublime-text-$SUBLIME_TEXT_VERSION/Packages/UnitTesting

script:
    - python $UNITTESTING/sbin/run.py $PACKAGE

notifications:
    email: false